Week8PicknPay/Controllers/RequestController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Week8PicknPay.Models;
using Week8PicknPay.Repository;

namespace Week8PicknPay.Controllers
{
    [Authorize]
    public class RequestController : Controller
    {
        private readonly IRequestForm _requestForm;

        public RequestController(IRequestForm requestForm)
        {
            _requestForm = requestForm;
        }

        public IActionResult Index()
        {
            return View();
        }

       
        public IActionResult Reply(Request request)
        {
            if(!ModelState.IsValid)
            {
                return View("Index");
            }
            _requestForm.SaveRequest(request);
            return RedirectToAction("Index", "Home");
        }


        public void NewsLetter(string email)
        {
            var result = _requestForm.SaveNewsLetterMail(email);
        }
    }
}

Week8PicknPay/Views/Shared/_Carousel.cshtml
<div class="carousel-holder" style="padding-right:2px">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img class="slide-image" src="~/Images/slide1.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/slide2.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/slide3.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/slide4.jpeg" alt="">
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
</div>

Week8PicknPay/Views/Shared/_Layout.cshtml
@using Week8PicknPay.Views.Shared.Components

<!DOCTYPE html>

<html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>@ViewBag.Title</title>
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
        <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
        <script src="~/lib/jquery/jquery.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css"
              integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA=="
              crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link href="~/content/site.css" rel="stylesheet" />
        <base href="~/" />
    </head>

    <body>
        <div class="container">

            <nav class="navbar navbar-inverse" role="navigation">
                    <div class=pull-left>
                        <a asp-controller="Home" asp-action="Index">
                            <img alt="Pick n Pay Stores'" src="~/Images/pick-n-pay-logo.jpg" style="margin: 9px; border-radius: 6px; height: 32px;" />
                        </a>
                    </div>
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                        @(await Html.RenderComponentAsync<NavSearch>(RenderMode.ServerPrerendered))

                        <div class="pull-right">
                            <ul class="nav navbar-nav">
                                @(await Html.RenderComponentAsync<CategoryMenu>(RenderMode.ServerPrerendered))
                                @(await Html.RenderComponentAsync<CartSummary>(RenderMode.ServerPrerendered))
                                <partial name="_LoginPartial" />
                            </ul>
                        </div>

                    </div>
            </nav>

            <div class="content-container">
                @RenderBody()
            </div>

            <footer>
                <div style="display: flex; justify-content: center;">
                    <div class="footer-links">
                        <a asp-controller="Home" asp-action="Index">Home</a>
                        <a href="/All/products">Products</a>
                        <a asp-controller="Request" asp-action="Index">Contact Us</a>
                    </div>
                </div>
                <div class="footer-copyright">
                    &copy; 2021 Aji Crafts, Inc - <a asp-area="" asp-page="/Privacy">Privacy</a>
                </div>
            </footer>

        </div>

        @RenderSection("Scripts", required: false)
        <script src="_framework/blazor.server.js"></script>
    </body>
</html>